name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: pub run test
      - name: Install Flutter
        run: git clone https://github.com/flutter/flutter.git --depth 1 -b beta
        if: success()
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
        if: success()
      - name: Compile for Web
        run: flutter build web
        if: success() 
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        if: success()
